// Write the Ask question history to a text file — `npm run ask:history`.
//
// The durable record is the ask_query_log table, because the app runs on
// serverless instances with a read-only filesystem: a file in the repo cannot
// be appended to at request time, and anything written to /tmp dies with the
// instance. So the file is a GENERATED VIEW of the log, regenerated on demand.
//
// It is worth generating because the questions a tenant actually types are the
// real specification for what Ask should cover — particularly the unanswered
// ones, which are a to-do list written by the people using it.
//
// Needs .env.local for the service-role key:
//   npm run ask:history            → every tenant
//   npm run ask:history -- <name>  → tenants whose name matches

import { writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import { createAdminClient } from '@/lib/supabase/admin'

const OUT = path.join(process.cwd(), 'docs', 'ask-queries.md')

type TopRow = {
  question: string
  answer_kind: string | null
  answer_title: string | null
  answered: boolean
  hits: number
  last_asked: string
}

async function main() {
  const filter = (process.argv[2] ?? '').toLowerCase()
  const admin = createAdminClient()

  const { data: tenants, error } = await admin.from('tenants').select('id, name').order('name')
  if (error) {
    console.error('Could not read tenants:', error.message)
    process.exit(1)
  }

  const wanted = (tenants ?? []).filter((t) => !filter || (t.name ?? '').toLowerCase().includes(filter))
  if (wanted.length === 0) {
    console.error(filter ? `No tenant matches "${filter}".` : 'No tenants found.')
    process.exit(1)
  }

  const lines: string[] = [
    '# Ask — question history',
    '',
    '_Generated by `npm run ask:history` from the `ask_query_log` table. Do not edit by hand;',
    'edits are overwritten on the next run._',
    '',
    'Every question typed into Ask, grouped per tenant, most-asked first. **Unanswered**',
    'questions are the ones the engine could not match — they are the backlog.',
    '',
  ]

  let totalAsked = 0
  let totalUnanswered = 0

  for (const tenant of wanted) {
    const { data, error: rpcError } = await admin.rpc('ask_top_questions', {
      p_tenant_id: tenant.id,
      p_limit: 500,
    })

    const rows = (data ?? []) as TopRow[]
    if (rpcError) {
      lines.push(`## ${tenant.name}`, '', `_Could not read history: ${rpcError.message}_`, '')
      continue
    }
    if (rows.length === 0) continue

    const asked = rows.reduce((s, r) => s + Number(r.hits || 0), 0)
    const unanswered = rows.filter((r) => !r.answered)
    totalAsked += asked
    totalUnanswered += unanswered.length

    lines.push(
      `## ${tenant.name}`,
      '',
      `${rows.length} distinct question${rows.length === 1 ? '' : 's'}, asked ${asked} time${asked === 1 ? '' : 's'}.`,
      '',
    )

    if (unanswered.length > 0) {
      lines.push(`### Unanswered (${unanswered.length})`, '')
      for (const r of unanswered) {
        lines.push(`- ${r.question}${r.hits > 1 ? `  _(asked ${r.hits}×)_` : ''}`)
      }
      lines.push('')
    }

    const answered = rows.filter((r) => r.answered)
    if (answered.length > 0) {
      lines.push(`### Answered (${answered.length})`, '')
      lines.push('| Question | Answered with | Times | Last asked |')
      lines.push('| --- | --- | ---: | --- |')
      for (const r of answered) {
        const what = r.answer_title || r.answer_kind || '—'
        const when = (r.last_asked ?? '').slice(0, 10)
        lines.push(`| ${escapeCell(r.question)} | ${escapeCell(what)} | ${r.hits} | ${when} |`)
      }
      lines.push('')
    }
  }

  if (totalAsked === 0) {
    lines.push('_No questions recorded yet._', '')
  }

  await mkdir(path.dirname(OUT), { recursive: true })
  await writeFile(OUT, lines.join('\n'), 'utf8')

  console.log(`Wrote ${OUT}`)
  console.log(`${wanted.length} tenant(s) · ${totalAsked} question(s) asked · ${totalUnanswered} distinct unanswered`)
}

/** A pipe in a question would break the markdown table. */
function escapeCell(v: string): string {
  return (v ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim()
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
